version:'3.1'

services:
	db:
	   image:postres:latest
           restart:always
	   container_name: psdb_container
           environment:
             POSTGRES_USER: postgres_user
      	     POSTGRES_PASSWORD: postgres_password
             POSTGRES_DB: postgres_db
             PGDATA: /var/lib/postgresql/data/pgdata
          ports:
            - '5004:5432'
          volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
        
        web:
	    image:nginx
            restart:always
            container_name: web_container
          ports:
	    - '8080:80'
    monitor:
           image: grafana/grafana-enterprise
    	   container_name: grafana
           restart: always
         ports:
          - '3000:3000'
